### ISSUE TITLE
cacheKey和requestId

### ISSUE THREAD

**Issue by woshiccm** [wzpziyi1/iOSNetwork#1]
cacheKey是否可以设置成是否cache,如果cache可以给个默认的值为url+params+时间戳的MD5加密的字符串，还有requestId是同样的东西，像你demo里演示的那种很难去设置一个Int类型并且保证不冲突，你觉得呢？

**Comment by wzpziyi1** [comment]
cacheKey在编写的时候是需要自己拼接的，最好是url+token+userId，我在自己的应用中是这么拼接的，确保其唯一。默认来说，cachekey为nil，是不会进行缓存的。额，之前版本实际应用中发现在并发处理上有问题，已经更新了。

**Comment by woshiccm** [comment]
老哥现在在哪个公司就职哇，是否考虑换工作，我们公司在招人，需要像你这样的大牛。。。

**Comment by wzpziyi1** [comment]
我现在在广州卓越，今年没想法跳槽啊，要买房、、

**Comment by woshiccm** [comment]
百度看到是培训结构，你是在那做教师吗？广州买房？

**Comment by wzpziyi1** [comment]
教育类企业，做中小学教育课外培训的
